// server/test.js
// Registers test-only socket handlers to keep server/app.js lean

function registerTestHandlers(socket, {
  convertTimestampToHumanReadableDate,
  //updateSnapshot,
  getFirebaseAssets,
  getFirebaseSettings,
  setLocalStats
}) {
  /* ----------------------------------------------------------------------------- */
  /* Load test                                                                     */
  /* ----------------------------------------------------------------------------- */
  socket.on('load-test:ping', async () => {
    const serverTimestamp = Date.now();
    const serverHumanReadableDate = await convertTimestampToHumanReadableDate(serverTimestamp);
    const token = 'gej2qhxkV6pdve2h';
    console.log('Load test pong', 'token:', token, 'timestamp:', serverHumanReadableDate);
    const data = {
      response: 'pong',
      program: [
        { "torch": false, "duration": 199.8 },
        { "torch": true,  "duration": 22.2 },
        { "torch": false, "duration": 11.1 },
        { "torch": true,  "duration": 22.2 },
        { "torch": false, "duration": 11.1 },
        { "torch": true,  "duration": 22.2 },
        { "torch": false, "duration": 344.1 },
        { "torch": true,  "duration": 22.2 },
        { "torch": false, "duration": 11.1 },
        { "torch": true,  "duration": 22.2 },
        { "torch": false, "duration": 11.1 },
        { "torch": true,  "duration": 22.2 },
        { "torch": false, "duration": 344.1 },
        { "torch": true,  "duration": 22.2 },
        { "torch": false, "duration": 11.1 },
        { "torch": true,  "duration": 22.2 },
        { "torch": false, "duration": 11.1 },
        { "torch": true,  "duration": 22.2 },
        { "torch": false, "duration": 344.1 },
        { "torch": true,  "duration": 22.2 },
        { "torch": false, "duration": 11.1 },
        { "torch": true,  "duration": 22.2 },
        { "torch": false, "duration": 11.1 },
        { "torch": true,  "duration": 22.2 },
        { "torch": false, "duration": 344.1 },
        { "torch": true,  "duration": 22.2 },
        { "torch": false, "duration": 11.1 },
        { "torch": true,  "duration": 22.2 },
        { "torch": false, "duration": 11.1 },
        { "torch": true,  "duration": 22.2 },
        { "torch": false, "duration": 310.08 },
        { "torch": true,  "duration": 199.8 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 333 },
        { "torch": false, "duration": 266.4 },
        { "torch": true,  "duration": 266.4 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 299.7 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 266.4 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 66.6 },
        { "torch": false, "duration": 99.9 },
        { "torch": true,  "duration": 399.6 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 366.3 },
        { "torch": false, "duration": 432.9 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 432.9 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 932.4 },
        { "torch": true,  "duration": 366.3 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 333 },
        { "torch": false, "duration": 932.4 },
        { "torch": true,  "duration": 333 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 199.79999999999998 },
        { "torch": true,  "duration": 399.59999999999997 },
        { "torch": false, "duration": 266.4 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 299.7 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 632.6999999999999 },
        { "torch": true,  "duration": 832.4999999999999 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 199.79999999999998 },
        { "torch": false, "duration": 99.89999999999999 },
        { "torch": true,  "duration": 99.89999999999999 },
        { "torch": false, "duration": 99.89999999999999 },
        { "torch": true,  "duration": 99.89999999999999 },
        { "torch": false, "duration": 233.09999999999997 },
        { "torch": true,  "duration": 499.49999999999994 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 266.4 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 599.4 },
        { "torch": true,  "duration": 333.0 },
        { "torch": false, "duration": 266.4 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 99.89999999999999 },
        { "torch": false, "duration": 99.89999999999999 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 199.79999999999998 },
        { "torch": true,  "duration": 399.59999999999997 },
        { "torch": false, "duration": 333.0 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 765.9 },
        { "torch": true,  "duration": 333.0 },
        { "torch": false, "duration": 266.4 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 233.09999999999997 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 199.79999999999998 },
        { "torch": false, "duration": 899.0999999999999 },
        { "torch": true,  "duration": 199.79999999999998 },
        { "torch": false, "duration": 199.79999999999998 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 66.6 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 66.6 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 99.89999999999999 },
        { "torch": false, "duration": 599.4 },
        { "torch": true,  "duration": 333.0 },
        { "torch": false, "duration": 366.29999999999995 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 632.6999999999999 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 199.79999999999998 },
        { "torch": false, "duration": 99.89999999999999 },
        { "torch": true,  "duration": 266.4 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 266.4 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 266.4 },
        { "torch": false, "duration": 66.6 },
        { "torch": true,  "duration": 266.4 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 266.4 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 266.4 },
        { "torch": false, "duration": 466.19999999999993 },
        { "torch": true,  "duration": 133.2 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 33.3 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 299.7 },
        { "torch": true,  "duration": 99.89999999999999 },
        { "torch": false, "duration": 99.89999999999999 },
        { "torch": true,  "duration": 99.89999999999999 },
        { "torch": false, "duration": 233.09999999999997 },
        { "torch": true,  "duration": 399.59999999999997 },
        { "torch": false, "duration": 2597.3999999999996 },
        { "torch": true,  "duration": 666.0 },
        { "torch": false, "duration": 2331.0 },
        { "torch": true,  "duration": 266.4 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 333.0 },
        { "torch": false, "duration": 366.29999999999995 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 99.89999999999999 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 366.29999999999995 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 66.6 },
        { "torch": false, "duration": 832.4999999999999 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 233.09999999999997 },
        { "torch": false, "duration": 99.89999999999999 },
        { "torch": true,  "duration": 99.89999999999999 },
        { "torch": false, "duration": 99.89999999999999 },
        { "torch": true,  "duration": 233.09999999999997 },
        { "torch": false, "duration": 399.59999999999997 },
        { "torch": true,  "duration": 266.4 },
        { "torch": false, "duration": 99.89999999999999 },
        { "torch": true,  "duration": 166.5 },
        { "torch": false, "duration": 133.2 },
        { "torch": true,  "duration": 66.6 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 166.5 },
        { "torch": true,  "duration": 33.3 },
        { "torch": false, "duration": 166.5 }
      ]
    };
    socket.emit('load-test:pong', { data: data, timestamp: serverTimestamp });
  });

  // socket on test-user-connected with no data
  socket.on('test-user-connected', async () => {
    let token = 'gej2qhxkV6pdve2h';
    let timestamp = convertTimestampToHumanReadableDate(Date.now());
    socket.data.token = token;
    socket.data.timestamp = timestamp;
    socket.data.role = 'user';
    socket.data.startedAt = timestamp;
    socket.data.firestoreRoot = 'lightShow';
    socket.data.displayName = 'Z -Amber';
    const assets = await getFirebaseAssets(token, socket.data.firestoreRoot);
    const settings = await getFirebaseSettings(token, socket.data.firestoreRoot);
    if (assets && settings) {
      socket.emit('assets-settings', assets, settings, socket.data.displayName || 'Unknown');
    } else {
      console.error('### test-user-connected: Assets or settings not found', 'token:', token, 'timestamp:', timestamp);
    }
    //updateSnapshot(socket, 'user_connected');
    setLocalStats(socket.data, 'user_connected');
  });

  socket.on('test-torch-connected', async () => {
    const humanReadableDate = await convertTimestampToHumanReadableDate(Date.now());
    const token = 'gej2qhxkV6pdve2h';
    console.log('Load test torch connected', 'token:', token, 'timestamp:', humanReadableDate);
    socket.data.torch = true;
    socket.data.token = token;
    socket.data.torchConnectedAt = humanReadableDate;
    //updateSnapshot(socket, 'torch_connected');
    setLocalStats(socket.data, 'torch_connected');
  });
}

module.exports = { registerTestHandlers };

